name: Deploy portfolio changes to S3 bucket

on: 
  push: 
    branches:
      - main

jobs: 
  build: 
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: mini-portfolio

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4

    - name: Install dependencies
      run: npm install

    - name: Build Website
      run: npm run build

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-west-2'
        
    - name: Copy to S3
      run: aws s3 sync ./build/. s3://hhphu.com
